### ISSUE TITLE
:pencil: Plan to develop APP in PC. 计划开发PC版APP 

### ISSUE THREAD

**Issue by tzfun** [tzfun/etcd-workbench#26]
网页版体验有一定局限性，为了提供更好的用户体验，接下来计划开发PC版APP程序，初步计划支持以下平台：

- Windows, windows_x86_64
- MacOS, darwin_aarch_64
- MacOS, darwin_x86_64

轻量、易上手一直是此项目创立以来的核心宗旨，PC版的界面使用体验不会比网页版差，只会更优。为了让APP更安全、轻量、性能好，APP项目计划使用 rust 开发，GUI使用 tauri，最终包体理想状态会在 10M 以内，期待APP版本的发布吧~ 😄 

**TODO**:

- [x] 创建app工程
- [x] 搭建工程基础环境：rust + tauri + tokio + vue + typescript + vuetify
- [x] etcd server基础连接并测试
- [x] `TLS`连接开发
- [x] `SSH`连接开发
- [x] 多Session连接与数据交互相关的rust接口开发
- [x] `KV`相关rust接口开发
- [x] `Auth`相关rust接口开发
- [x] `Maintenance`相关rust接口开发
- [x] `Cluster`相关rust接口开发
- [x] `Lease`相关rust接口开发
- [x] 搭建APP基础界面，确定界面布局
- [x] Windows版和Mac版的 header适配，包含原生按钮模拟或兼容
- [x] 多Session界面开发，并与rust联通调试
- [x] Cluster界面开发，并与rust联通测试
- [x] ETCD连接界面开发，并与rust联通调试
- [x] KV编辑界面开发，并与rust联调调试
- [x] KV历史版本功能预览开发，并与rust联通调试
- [x] 用户权限界面开发，并与rust联通调试
- [x] 角色权限界面开发，并与rust联通调试
- [x] Lease界面开发，并与rust联通调试
- [x] #31
- [x] 数据备份功能开发
- [x] 黑白主题切换功能开发
- [x] 设置窗口及功能开发
- [x] 版本信息与历史记录展示功能与界面
- [x] 打包 `windows_x86_64` 并做单元测试
- [x] 打包 `darwin_x86_64` 并做单元测试
- [x] 打包 `darwin_aarch_64` 并做单元测试
- [x] 在线更新功能开发
- [x] 发布 Beta 版
- [x] 发布 Release 版

**Comment by tzfun** [comment]
已发布预览版本：[App-1.0.0](https://github.com/tzfun/etcd-workbench/releases/tag/App-1.0.0)

**Comment by tzfun** [comment]
已发布正式版本：[App-1.0.1](https://github.com/tzfun/etcd-workbench/releases/tag/App-1.0.1)

**Comment by AGou-ops** [comment]
1.0.1版本客户端展开节点，查看key对应值时有卡顿，网页版正常，很流畅.

MacOS 14.6.1
m1 pro芯片.
